#! /bin/bash
SYS=`uname -r`
if [ -f /etc/debian_version ]; then
    OS=debian  
elif [ -f /etc/redhat-release ]; then
    OS=redhat
    systemctl stop firewalld.service
else
    OS=unknown
fi    

MACHINE_TYPE=`uname -m`
if [ ${MACHINE_TYPE} != 'x86_64' ]; then
  echo "ERROR, only 64bit operating systems are supported, please reinstall x86 64 bit OS"
  exit 1
fi



if [ -d /mnt/huge ]; then
  echo >> /dev/null
else
  echo "Creating huge node"
  mkdir -p /mnt/huge
fi

if ! mount | grep hugetlbfs >> /dev/null ; then 
    mount -t hugetlbfs nodev /mnt/huge  
fi  


for file in /sys/devices/system/node/node0/hugepages/hugepages-2048kB/nr_hugepages /sys/devices/system/node/node1/hugepages/hugepages-2048kB/nr_hugepages ; do
    if [ -e $file ] ; then 
        if [ "$(cat $file)" != "2048" ] ; then
          echo 2048 > $file
        fi  
    fi
done

modprobe vfio-pci

# try to bind the ports from the configuration file (new DPDK)
PARENT_ARGS="$0 $@"
(/usr/bin/python -V &> /dev/null && ./dpdk_setup_ports.py --parent "$PARENT_ARGS") ||
    (/usr/bin/python3 -V &> /dev/null && /usr/bin/python3 dpdk_setup_ports.py --parent "$PARENT_ARGS") || exit 1
